// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieCatalogMVC.Data;

#nullable disable

namespace MovieCatalogMVC.Data.Migrations
{
    [DbContext(typeof(MovieCatalogMVCContext))]
    [Migration("20240909023740_SeedMoviesFix")]
    partial class SeedMoviesFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "95884caa-2428-4cfc-943e-ac987fc94330",
                            Email = "user1@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@EXAMPLE.COM",
                            NormalizedUserName = "USER1@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAnLu+TDNR+KNst8WfM/tcbDVdV4pylCDuEeQNostw0S45/7T1bpgEV1oNEAwCJKHg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6b8ed6db-4bd7-4eaf-9719-954d3d413f47",
                            TwoFactorEnabled = false,
                            UserName = "user1@example.com"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c7a899e1-76ff-4645-aa3c-ecb4767c1c6d",
                            Email = "user2@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER2@EXAMPLE.COM",
                            NormalizedUserName = "USER2@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOf8gr9Fdo3ARDeYYxwgGHYyW7G05fkV15XjufdCilkj0IIRZFHBEVL4QzZBxAJImg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "47817399-34c0-4fc5-b148-9134db9cb5c1",
                            TwoFactorEnabled = false,
                            UserName = "user2@example.com"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "23ecda42-c885-494f-9d8e-cb560bb8a6f9",
                            Email = "user3@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER3@EXAMPLE.COM",
                            NormalizedUserName = "USER3@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAkhSFuuHWOWmGqXBDBJRNXT67xEjfk8CJMp4QoeevUsm+3P/JycUP801LEj9zpQ2A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f26ef962-fd9a-4d18-a480-bea70d768508",
                            TwoFactorEnabled = false,
                            UserName = "user3@example.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Name = "Action"
                        },
                        new
                        {
                            GenreId = 2,
                            Name = "Comedy"
                        },
                        new
                        {
                            GenreId = 3,
                            Name = "Drama"
                        },
                        new
                        {
                            GenreId = 4,
                            Name = "Fantasy"
                        },
                        new
                        {
                            GenreId = 5,
                            Name = "Horror"
                        },
                        new
                        {
                            GenreId = 6,
                            Name = "Mystery"
                        },
                        new
                        {
                            GenreId = 7,
                            Name = "Romance"
                        },
                        new
                        {
                            GenreId = 8,
                            Name = "Thriller"
                        },
                        new
                        {
                            GenreId = 9,
                            Name = "Western"
                        },
                        new
                        {
                            GenreId = 10,
                            Name = "Documentary"
                        },
                        new
                        {
                            GenreId = 11,
                            Name = "Animation"
                        },
                        new
                        {
                            GenreId = 12,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            GenreId = 13,
                            Name = "Adventure"
                        },
                        new
                        {
                            GenreId = 14,
                            Name = "Crime"
                        },
                        new
                        {
                            GenreId = 15,
                            Name = "Musical"
                        });
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            GenreId = 1,
                            ReleaseDate = new DateTime(2015, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mad Max: Fury Road"
                        },
                        new
                        {
                            MovieId = 2,
                            GenreId = 1,
                            ReleaseDate = new DateTime(2014, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "John Wick"
                        },
                        new
                        {
                            MovieId = 3,
                            GenreId = 1,
                            ReleaseDate = new DateTime(1988, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Die Hard"
                        },
                        new
                        {
                            MovieId = 4,
                            GenreId = 1,
                            ReleaseDate = new DateTime(2008, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            MovieId = 5,
                            GenreId = 2,
                            ReleaseDate = new DateTime(2007, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Superbad"
                        },
                        new
                        {
                            MovieId = 6,
                            GenreId = 2,
                            ReleaseDate = new DateTime(2014, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Grand Budapest Hotel"
                        },
                        new
                        {
                            MovieId = 7,
                            GenreId = 2,
                            ReleaseDate = new DateTime(2008, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Step Brothers"
                        },
                        new
                        {
                            MovieId = 8,
                            GenreId = 2,
                            ReleaseDate = new DateTime(2004, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Anchorman: The Legend of Ron Burgundy"
                        },
                        new
                        {
                            MovieId = 9,
                            GenreId = 3,
                            ReleaseDate = new DateTime(1994, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            MovieId = 10,
                            GenreId = 3,
                            ReleaseDate = new DateTime(1994, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            MovieId = 11,
                            GenreId = 3,
                            ReleaseDate = new DateTime(1972, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Godfather"
                        },
                        new
                        {
                            MovieId = 12,
                            GenreId = 3,
                            ReleaseDate = new DateTime(2001, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "A Beautiful Mind"
                        },
                        new
                        {
                            MovieId = 13,
                            GenreId = 4,
                            ReleaseDate = new DateTime(2001, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Lord of the Rings: The Fellowship of the Ring"
                        },
                        new
                        {
                            MovieId = 14,
                            GenreId = 4,
                            ReleaseDate = new DateTime(2001, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            MovieId = 15,
                            GenreId = 4,
                            ReleaseDate = new DateTime(2006, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pan's Labyrinth"
                        },
                        new
                        {
                            MovieId = 16,
                            GenreId = 4,
                            ReleaseDate = new DateTime(2001, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Spirited Away"
                        },
                        new
                        {
                            MovieId = 17,
                            GenreId = 5,
                            ReleaseDate = new DateTime(1973, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Exorcist"
                        },
                        new
                        {
                            MovieId = 18,
                            GenreId = 5,
                            ReleaseDate = new DateTime(2017, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Get Out"
                        },
                        new
                        {
                            MovieId = 19,
                            GenreId = 5,
                            ReleaseDate = new DateTime(2018, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "A Quiet Place"
                        },
                        new
                        {
                            MovieId = 20,
                            GenreId = 5,
                            ReleaseDate = new DateTime(2018, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hereditary"
                        },
                        new
                        {
                            MovieId = 21,
                            GenreId = 6,
                            ReleaseDate = new DateTime(2019, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Knives Out"
                        },
                        new
                        {
                            MovieId = 22,
                            GenreId = 6,
                            ReleaseDate = new DateTime(1995, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Se7en"
                        },
                        new
                        {
                            MovieId = 23,
                            GenreId = 6,
                            ReleaseDate = new DateTime(2014, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gone Girl"
                        },
                        new
                        {
                            MovieId = 24,
                            GenreId = 7,
                            ReleaseDate = new DateTime(2004, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Notebook"
                        },
                        new
                        {
                            MovieId = 25,
                            GenreId = 7,
                            ReleaseDate = new DateTime(2005, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            MovieId = 26,
                            GenreId = 7,
                            ReleaseDate = new DateTime(2016, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "La La Land"
                        },
                        new
                        {
                            MovieId = 27,
                            GenreId = 8,
                            ReleaseDate = new DateTime(1991, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Silence of the Lambs"
                        },
                        new
                        {
                            MovieId = 28,
                            GenreId = 8,
                            ReleaseDate = new DateTime(1999, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fight Club"
                        },
                        new
                        {
                            MovieId = 29,
                            GenreId = 8,
                            ReleaseDate = new DateTime(2013, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Prisoners"
                        },
                        new
                        {
                            MovieId = 30,
                            GenreId = 9,
                            ReleaseDate = new DateTime(1966, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Good, the Bad and the Ugly"
                        },
                        new
                        {
                            MovieId = 31,
                            GenreId = 9,
                            ReleaseDate = new DateTime(1992, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Unforgiven"
                        },
                        new
                        {
                            MovieId = 32,
                            GenreId = 9,
                            ReleaseDate = new DateTime(2010, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "True Grit"
                        },
                        new
                        {
                            MovieId = 33,
                            GenreId = 10,
                            ReleaseDate = new DateTime(2016, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "13th"
                        },
                        new
                        {
                            MovieId = 34,
                            GenreId = 10,
                            ReleaseDate = new DateTime(2018, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Free Solo"
                        },
                        new
                        {
                            MovieId = 35,
                            GenreId = 10,
                            ReleaseDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Social Dilemma"
                        },
                        new
                        {
                            MovieId = 36,
                            GenreId = 11,
                            ReleaseDate = new DateTime(1995, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Toy Story"
                        },
                        new
                        {
                            MovieId = 37,
                            GenreId = 11,
                            ReleaseDate = new DateTime(2003, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Finding Nemo"
                        },
                        new
                        {
                            MovieId = 38,
                            GenreId = 11,
                            ReleaseDate = new DateTime(2001, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Spirited Away"
                        },
                        new
                        {
                            MovieId = 39,
                            GenreId = 12,
                            ReleaseDate = new DateTime(2010, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception"
                        },
                        new
                        {
                            MovieId = 40,
                            GenreId = 12,
                            ReleaseDate = new DateTime(2017, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Blade Runner 2049"
                        },
                        new
                        {
                            MovieId = 41,
                            GenreId = 12,
                            ReleaseDate = new DateTime(1999, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Matrix"
                        },
                        new
                        {
                            MovieId = 42,
                            GenreId = 13,
                            ReleaseDate = new DateTime(1993, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jurassic Park"
                        },
                        new
                        {
                            MovieId = 43,
                            GenreId = 13,
                            ReleaseDate = new DateTime(1981, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Indiana Jones: Raiders of the Lost Ark"
                        },
                        new
                        {
                            MovieId = 44,
                            GenreId = 13,
                            ReleaseDate = new DateTime(1995, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jumanji"
                        },
                        new
                        {
                            MovieId = 45,
                            GenreId = 14,
                            ReleaseDate = new DateTime(1972, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Godfather"
                        },
                        new
                        {
                            MovieId = 46,
                            GenreId = 14,
                            ReleaseDate = new DateTime(1990, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Goodfellas"
                        },
                        new
                        {
                            MovieId = 47,
                            GenreId = 14,
                            ReleaseDate = new DateTime(1994, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            MovieId = 48,
                            GenreId = 15,
                            ReleaseDate = new DateTime(1965, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Sound of Music"
                        },
                        new
                        {
                            MovieId = 49,
                            GenreId = 15,
                            ReleaseDate = new DateTime(2016, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "La La Land"
                        },
                        new
                        {
                            MovieId = 50,
                            GenreId = 15,
                            ReleaseDate = new DateTime(2002, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Chicago"
                        });
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.MoviesStreamings", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("StreamingId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "StreamingId");

                    b.HasIndex("StreamingId");

                    b.ToTable("MoviesStreamings");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 1,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 2,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 2,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 3,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 3,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 4,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 4,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 5,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 6,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 7,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 7,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 8,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 9,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 9,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 10,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 11,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 12,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 13,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 14,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 15,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 16,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 17,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 18,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 19,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 20,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 21,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 22,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 23,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 24,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 25,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 26,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 27,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 28,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 29,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 30,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 31,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 32,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 33,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 34,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 35,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 36,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 37,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 38,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 39,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 40,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 41,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 42,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 43,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 44,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 45,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 46,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 47,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 48,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 49,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 50,
                            StreamingId = 5
                        });
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReviewId");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Streaming", b =>
                {
                    b.Property<int>("StreamingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StreamingId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StreamingId");

                    b.ToTable("Streamings");

                    b.HasData(
                        new
                        {
                            StreamingId = 1,
                            Name = "Netflix"
                        },
                        new
                        {
                            StreamingId = 2,
                            Name = "Amazon Prime Video"
                        },
                        new
                        {
                            StreamingId = 3,
                            Name = "Disney+"
                        },
                        new
                        {
                            StreamingId = 4,
                            Name = "HBO Max"
                        },
                        new
                        {
                            StreamingId = 5,
                            Name = "Hulu"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Movie", b =>
                {
                    b.HasOne("MovieCatalogMVC.Entities.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.MoviesStreamings", b =>
                {
                    b.HasOne("MovieCatalogMVC.Entities.Movie", "Movie")
                        .WithMany("MoviesStreamings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieCatalogMVC.Entities.Streaming", "Streaming")
                        .WithMany("MoviesStreamings")
                        .HasForeignKey("StreamingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Streaming");
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Review", b =>
                {
                    b.HasOne("MovieCatalogMVC.Entities.Movie", "Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Movie", b =>
                {
                    b.Navigation("MoviesStreamings");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Streaming", b =>
                {
                    b.Navigation("MoviesStreamings");
                });
#pragma warning restore 612, 618
        }
    }
}
