// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieCatalogMVC.Data;

#nullable disable

namespace MovieCatalogMVC.Data.Migrations
{
    [DbContext(typeof(MovieCatalogMVCContext))]
    [Migration("20240909024350_SeedReviews")]
    partial class SeedReviews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c7d5359e-092e-4bb6-a229-2eea2b23886a",
                            Email = "user1@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@EXAMPLE.COM",
                            NormalizedUserName = "USER1@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBARLLbdHUurat7gsrKdk133i3ockXCRze9/UgZAfLNViMyQUFmRlvikuR4sC62XKQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "acb7e91d-fa8e-4afc-b081-0b4a258b3f6e",
                            TwoFactorEnabled = false,
                            UserName = "user1@example.com"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7cae9434-a352-4f52-a414-4353c5a20231",
                            Email = "user2@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER2@EXAMPLE.COM",
                            NormalizedUserName = "USER2@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBvhG5T/BOTA6VKGmReh3cURyG3tz9YNwHqkuKDOL/iz66Wwe43/HImWCS/7H4N8SQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "50910133-18d0-466f-ac68-b8982d918f6a",
                            TwoFactorEnabled = false,
                            UserName = "user2@example.com"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "026c3554-4ab1-4d52-b57a-1f45e2101704",
                            Email = "user3@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER3@EXAMPLE.COM",
                            NormalizedUserName = "USER3@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHEr4Se19ZoX2eYc4IdKia7wZnH7sth17vFN9yDvS8j9ztdbk+F9IHg2JVsU4zglOA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e74d5eea-530c-48c9-aae6-4b161120c74e",
                            TwoFactorEnabled = false,
                            UserName = "user3@example.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Name = "Action"
                        },
                        new
                        {
                            GenreId = 2,
                            Name = "Comedy"
                        },
                        new
                        {
                            GenreId = 3,
                            Name = "Drama"
                        },
                        new
                        {
                            GenreId = 4,
                            Name = "Fantasy"
                        },
                        new
                        {
                            GenreId = 5,
                            Name = "Horror"
                        },
                        new
                        {
                            GenreId = 6,
                            Name = "Mystery"
                        },
                        new
                        {
                            GenreId = 7,
                            Name = "Romance"
                        },
                        new
                        {
                            GenreId = 8,
                            Name = "Thriller"
                        },
                        new
                        {
                            GenreId = 9,
                            Name = "Western"
                        },
                        new
                        {
                            GenreId = 10,
                            Name = "Documentary"
                        },
                        new
                        {
                            GenreId = 11,
                            Name = "Animation"
                        },
                        new
                        {
                            GenreId = 12,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            GenreId = 13,
                            Name = "Adventure"
                        },
                        new
                        {
                            GenreId = 14,
                            Name = "Crime"
                        },
                        new
                        {
                            GenreId = 15,
                            Name = "Musical"
                        });
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            GenreId = 1,
                            ReleaseDate = new DateTime(2015, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mad Max: Fury Road"
                        },
                        new
                        {
                            MovieId = 2,
                            GenreId = 1,
                            ReleaseDate = new DateTime(2014, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "John Wick"
                        },
                        new
                        {
                            MovieId = 3,
                            GenreId = 1,
                            ReleaseDate = new DateTime(1988, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Die Hard"
                        },
                        new
                        {
                            MovieId = 4,
                            GenreId = 1,
                            ReleaseDate = new DateTime(2008, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            MovieId = 5,
                            GenreId = 2,
                            ReleaseDate = new DateTime(2007, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Superbad"
                        },
                        new
                        {
                            MovieId = 6,
                            GenreId = 2,
                            ReleaseDate = new DateTime(2014, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Grand Budapest Hotel"
                        },
                        new
                        {
                            MovieId = 7,
                            GenreId = 2,
                            ReleaseDate = new DateTime(2008, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Step Brothers"
                        },
                        new
                        {
                            MovieId = 8,
                            GenreId = 2,
                            ReleaseDate = new DateTime(2004, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Anchorman: The Legend of Ron Burgundy"
                        },
                        new
                        {
                            MovieId = 9,
                            GenreId = 3,
                            ReleaseDate = new DateTime(1994, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            MovieId = 10,
                            GenreId = 3,
                            ReleaseDate = new DateTime(1994, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            MovieId = 11,
                            GenreId = 3,
                            ReleaseDate = new DateTime(1972, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Godfather"
                        },
                        new
                        {
                            MovieId = 12,
                            GenreId = 3,
                            ReleaseDate = new DateTime(2001, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "A Beautiful Mind"
                        },
                        new
                        {
                            MovieId = 13,
                            GenreId = 4,
                            ReleaseDate = new DateTime(2001, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Lord of the Rings: The Fellowship of the Ring"
                        },
                        new
                        {
                            MovieId = 14,
                            GenreId = 4,
                            ReleaseDate = new DateTime(2001, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            MovieId = 15,
                            GenreId = 4,
                            ReleaseDate = new DateTime(2006, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pan's Labyrinth"
                        },
                        new
                        {
                            MovieId = 16,
                            GenreId = 4,
                            ReleaseDate = new DateTime(2001, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Spirited Away"
                        },
                        new
                        {
                            MovieId = 17,
                            GenreId = 5,
                            ReleaseDate = new DateTime(1973, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Exorcist"
                        },
                        new
                        {
                            MovieId = 18,
                            GenreId = 5,
                            ReleaseDate = new DateTime(2017, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Get Out"
                        },
                        new
                        {
                            MovieId = 19,
                            GenreId = 5,
                            ReleaseDate = new DateTime(2018, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "A Quiet Place"
                        },
                        new
                        {
                            MovieId = 20,
                            GenreId = 5,
                            ReleaseDate = new DateTime(2018, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hereditary"
                        },
                        new
                        {
                            MovieId = 21,
                            GenreId = 6,
                            ReleaseDate = new DateTime(2019, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Knives Out"
                        },
                        new
                        {
                            MovieId = 22,
                            GenreId = 6,
                            ReleaseDate = new DateTime(1995, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Se7en"
                        },
                        new
                        {
                            MovieId = 23,
                            GenreId = 6,
                            ReleaseDate = new DateTime(2014, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gone Girl"
                        },
                        new
                        {
                            MovieId = 24,
                            GenreId = 7,
                            ReleaseDate = new DateTime(2004, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Notebook"
                        },
                        new
                        {
                            MovieId = 25,
                            GenreId = 7,
                            ReleaseDate = new DateTime(2005, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            MovieId = 26,
                            GenreId = 7,
                            ReleaseDate = new DateTime(2016, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "La La Land"
                        },
                        new
                        {
                            MovieId = 27,
                            GenreId = 8,
                            ReleaseDate = new DateTime(1991, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Silence of the Lambs"
                        },
                        new
                        {
                            MovieId = 28,
                            GenreId = 8,
                            ReleaseDate = new DateTime(1999, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fight Club"
                        },
                        new
                        {
                            MovieId = 29,
                            GenreId = 8,
                            ReleaseDate = new DateTime(2013, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Prisoners"
                        },
                        new
                        {
                            MovieId = 30,
                            GenreId = 9,
                            ReleaseDate = new DateTime(1966, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Good, the Bad and the Ugly"
                        },
                        new
                        {
                            MovieId = 31,
                            GenreId = 9,
                            ReleaseDate = new DateTime(1992, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Unforgiven"
                        },
                        new
                        {
                            MovieId = 32,
                            GenreId = 9,
                            ReleaseDate = new DateTime(2010, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "True Grit"
                        },
                        new
                        {
                            MovieId = 33,
                            GenreId = 10,
                            ReleaseDate = new DateTime(2016, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "13th"
                        },
                        new
                        {
                            MovieId = 34,
                            GenreId = 10,
                            ReleaseDate = new DateTime(2018, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Free Solo"
                        },
                        new
                        {
                            MovieId = 35,
                            GenreId = 10,
                            ReleaseDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Social Dilemma"
                        },
                        new
                        {
                            MovieId = 36,
                            GenreId = 11,
                            ReleaseDate = new DateTime(1995, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Toy Story"
                        },
                        new
                        {
                            MovieId = 37,
                            GenreId = 11,
                            ReleaseDate = new DateTime(2003, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Finding Nemo"
                        },
                        new
                        {
                            MovieId = 38,
                            GenreId = 11,
                            ReleaseDate = new DateTime(2001, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Spirited Away"
                        },
                        new
                        {
                            MovieId = 39,
                            GenreId = 12,
                            ReleaseDate = new DateTime(2010, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception"
                        },
                        new
                        {
                            MovieId = 40,
                            GenreId = 12,
                            ReleaseDate = new DateTime(2017, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Blade Runner 2049"
                        },
                        new
                        {
                            MovieId = 41,
                            GenreId = 12,
                            ReleaseDate = new DateTime(1999, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Matrix"
                        },
                        new
                        {
                            MovieId = 42,
                            GenreId = 13,
                            ReleaseDate = new DateTime(1993, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jurassic Park"
                        },
                        new
                        {
                            MovieId = 43,
                            GenreId = 13,
                            ReleaseDate = new DateTime(1981, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Indiana Jones: Raiders of the Lost Ark"
                        },
                        new
                        {
                            MovieId = 44,
                            GenreId = 13,
                            ReleaseDate = new DateTime(1995, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jumanji"
                        },
                        new
                        {
                            MovieId = 45,
                            GenreId = 14,
                            ReleaseDate = new DateTime(1972, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Godfather"
                        },
                        new
                        {
                            MovieId = 46,
                            GenreId = 14,
                            ReleaseDate = new DateTime(1990, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Goodfellas"
                        },
                        new
                        {
                            MovieId = 47,
                            GenreId = 14,
                            ReleaseDate = new DateTime(1994, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            MovieId = 48,
                            GenreId = 15,
                            ReleaseDate = new DateTime(1965, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Sound of Music"
                        },
                        new
                        {
                            MovieId = 49,
                            GenreId = 15,
                            ReleaseDate = new DateTime(2016, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "La La Land"
                        },
                        new
                        {
                            MovieId = 50,
                            GenreId = 15,
                            ReleaseDate = new DateTime(2002, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Chicago"
                        });
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.MoviesStreamings", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("StreamingId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "StreamingId");

                    b.HasIndex("StreamingId");

                    b.ToTable("MoviesStreamings");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 1,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 2,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 2,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 3,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 3,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 4,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 4,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 5,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 6,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 7,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 7,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 8,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 9,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 9,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 10,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 11,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 12,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 13,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 14,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 15,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 16,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 17,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 18,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 19,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 20,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 21,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 22,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 23,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 24,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 25,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 26,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 27,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 28,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 29,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 30,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 31,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 32,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 33,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 34,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 35,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 36,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 37,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 38,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 39,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 40,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 41,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 42,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 43,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 44,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 45,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 46,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 47,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 48,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 49,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 50,
                            StreamingId = 5
                        });
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReviewId");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = -339852750,
                            Comment = "A masterpiece!",
                            MovieId = 1,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(206),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -902496200,
                            Comment = "Not bad, but could be better.",
                            MovieId = 1,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(7522),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 1309291082,
                            Comment = "Would not recommend.",
                            MovieId = 2,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(7578),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -1261472015,
                            Comment = "Great movie!",
                            MovieId = 2,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(7613),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -165260580,
                            Comment = "Really enjoyed it.",
                            MovieId = 3,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(7767),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 226730468,
                            Comment = "Really enjoyed it.",
                            MovieId = 3,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(7830),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 1105735894,
                            Comment = "",
                            MovieId = 4,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(7933),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1404089802,
                            Comment = "Would not recommend.",
                            MovieId = 4,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(7966),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 18987959,
                            Comment = "Really enjoyed it.",
                            MovieId = 5,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(7989),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 987024461,
                            Comment = "Great movie!",
                            MovieId = 5,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(8018),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1985152183,
                            Comment = "Would not recommend.",
                            MovieId = 6,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(8048),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -1998793611,
                            Comment = "Really enjoyed it.",
                            MovieId = 6,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(8149),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1496018839,
                            Comment = "Would not recommend.",
                            MovieId = 7,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(8177),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1251031982,
                            Comment = "Great movie!",
                            MovieId = 7,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(8200),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1275479114,
                            Comment = "Really enjoyed it.",
                            MovieId = 8,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(8227),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 730658803,
                            Comment = "Not bad, but could be better.",
                            MovieId = 8,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(8264),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1351712131,
                            Comment = "Not bad, but could be better.",
                            MovieId = 9,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(8288),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1967455870,
                            Comment = "Not bad, but could be better.",
                            MovieId = 9,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(8311),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 805678142,
                            Comment = "Would not recommend.",
                            MovieId = 10,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(8335),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -1571687970,
                            Comment = "",
                            MovieId = 10,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(8358),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 490993528,
                            Comment = "",
                            MovieId = 11,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(8381),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 2042299912,
                            Comment = "Would not recommend.",
                            MovieId = 11,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(8403),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 2089587694,
                            Comment = "Would not recommend.",
                            MovieId = 12,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(8428),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1038395819,
                            Comment = "Really enjoyed it.",
                            MovieId = 12,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(8450),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 431068365,
                            Comment = "A masterpiece!",
                            MovieId = 13,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(8473),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -3618904,
                            Comment = "Great movie!",
                            MovieId = 13,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(8600),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -303744426,
                            Comment = "Not bad, but could be better.",
                            MovieId = 14,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(8707),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -124558288,
                            Comment = "Not bad, but could be better.",
                            MovieId = 14,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(8736),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -247395953,
                            Comment = "Would not recommend.",
                            MovieId = 15,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(8841),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1447058069,
                            Comment = "Great movie!",
                            MovieId = 15,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(8883),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 1593036289,
                            Comment = "",
                            MovieId = 16,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(8934),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 742930797,
                            Comment = "",
                            MovieId = 16,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(8959),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 720598744,
                            Comment = "Not bad, but could be better.",
                            MovieId = 17,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(8981),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 198681206,
                            Comment = "Really enjoyed it.",
                            MovieId = 17,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9006),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1480694261,
                            Comment = "",
                            MovieId = 18,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9029),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -143778457,
                            Comment = "A masterpiece!",
                            MovieId = 18,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9052),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 349547201,
                            Comment = "",
                            MovieId = 19,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9075),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1170636328,
                            Comment = "Really enjoyed it.",
                            MovieId = 19,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9097),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 2096000787,
                            Comment = "Really enjoyed it.",
                            MovieId = 20,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9123),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1376927856,
                            Comment = "A masterpiece!",
                            MovieId = 20,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9146),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -1181304867,
                            Comment = "Not bad, but could be better.",
                            MovieId = 21,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9169),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -911101101,
                            Comment = "Would not recommend.",
                            MovieId = 21,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9192),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 683695248,
                            Comment = "",
                            MovieId = 22,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9215),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -1864001702,
                            Comment = "Not bad, but could be better.",
                            MovieId = 22,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9237),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -1352240908,
                            Comment = "",
                            MovieId = 23,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9260),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -1149159625,
                            Comment = "Not bad, but could be better.",
                            MovieId = 23,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9283),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -688167549,
                            Comment = "A masterpiece!",
                            MovieId = 24,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9308),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -865821447,
                            Comment = "",
                            MovieId = 24,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9331),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -173752191,
                            Comment = "A masterpiece!",
                            MovieId = 25,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9354),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 104483586,
                            Comment = "Great movie!",
                            MovieId = 25,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9377),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 951340184,
                            Comment = "Really enjoyed it.",
                            MovieId = 26,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9400),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -295109688,
                            Comment = "A masterpiece!",
                            MovieId = 26,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9423),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 391451384,
                            Comment = "",
                            MovieId = 27,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9446),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1937613530,
                            Comment = "Really enjoyed it.",
                            MovieId = 27,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9468),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 1483896213,
                            Comment = "A masterpiece!",
                            MovieId = 28,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9530),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -456468176,
                            Comment = "Really enjoyed it.",
                            MovieId = 28,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9553),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 954504254,
                            Comment = "Not bad, but could be better.",
                            MovieId = 29,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9577),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -662180432,
                            Comment = "Great movie!",
                            MovieId = 29,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9599),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 592904769,
                            Comment = "Would not recommend.",
                            MovieId = 30,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9628),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -681301126,
                            Comment = "",
                            MovieId = 30,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9651),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -1032801216,
                            Comment = "",
                            MovieId = 31,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9674),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -434733164,
                            Comment = "Not bad, but could be better.",
                            MovieId = 31,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9697),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 22501509,
                            Comment = "Not bad, but could be better.",
                            MovieId = 32,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9723),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -1271345463,
                            Comment = "Not bad, but could be better.",
                            MovieId = 32,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9745),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -1668367387,
                            Comment = "",
                            MovieId = 33,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9768),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1006778750,
                            Comment = "Not bad, but could be better.",
                            MovieId = 33,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9793),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -428953596,
                            Comment = "A masterpiece!",
                            MovieId = 34,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9816),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -896650129,
                            Comment = "Would not recommend.",
                            MovieId = 34,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9839),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -322139031,
                            Comment = "Not bad, but could be better.",
                            MovieId = 35,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9862),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -1934488938,
                            Comment = "Would not recommend.",
                            MovieId = 35,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9885),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1910664838,
                            Comment = "Great movie!",
                            MovieId = 36,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9910),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1770342286,
                            Comment = "A masterpiece!",
                            MovieId = 36,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9933),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -184998244,
                            Comment = "Really enjoyed it.",
                            MovieId = 37,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9956),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -1801038450,
                            Comment = "A masterpiece!",
                            MovieId = 37,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 123, DateTimeKind.Local).AddTicks(9979),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 747592718,
                            Comment = "",
                            MovieId = 38,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 124, DateTimeKind.Local).AddTicks(1),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -915048420,
                            Comment = "",
                            MovieId = 38,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 124, DateTimeKind.Local).AddTicks(24),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -326985556,
                            Comment = "",
                            MovieId = 39,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 124, DateTimeKind.Local).AddTicks(47),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -698299737,
                            Comment = "Great movie!",
                            MovieId = 39,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 124, DateTimeKind.Local).AddTicks(92),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -1355269795,
                            Comment = "Really enjoyed it.",
                            MovieId = 40,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 124, DateTimeKind.Local).AddTicks(118),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 174216490,
                            Comment = "",
                            MovieId = 40,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 124, DateTimeKind.Local).AddTicks(141),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -811296574,
                            Comment = "Not bad, but could be better.",
                            MovieId = 41,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 124, DateTimeKind.Local).AddTicks(164),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -2042504858,
                            Comment = "Would not recommend.",
                            MovieId = 41,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 124, DateTimeKind.Local).AddTicks(188),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -1532410608,
                            Comment = "A masterpiece!",
                            MovieId = 42,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 124, DateTimeKind.Local).AddTicks(211),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 1450012408,
                            Comment = "Really enjoyed it.",
                            MovieId = 42,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 124, DateTimeKind.Local).AddTicks(234),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1544443931,
                            Comment = "",
                            MovieId = 43,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 124, DateTimeKind.Local).AddTicks(257),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -1215688623,
                            Comment = "Not bad, but could be better.",
                            MovieId = 43,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 124, DateTimeKind.Local).AddTicks(280),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1068947443,
                            Comment = "A masterpiece!",
                            MovieId = 44,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 124, DateTimeKind.Local).AddTicks(306),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 206877958,
                            Comment = "Would not recommend.",
                            MovieId = 44,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 124, DateTimeKind.Local).AddTicks(330),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -305036750,
                            Comment = "Great movie!",
                            MovieId = 45,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 124, DateTimeKind.Local).AddTicks(353),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 238171546,
                            Comment = "Really enjoyed it.",
                            MovieId = 45,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 124, DateTimeKind.Local).AddTicks(375),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -543996011,
                            Comment = "",
                            MovieId = 46,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 124, DateTimeKind.Local).AddTicks(398),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -293836472,
                            Comment = "",
                            MovieId = 46,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 124, DateTimeKind.Local).AddTicks(421),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 1796965965,
                            Comment = "Great movie!",
                            MovieId = 47,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 124, DateTimeKind.Local).AddTicks(444),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 135134003,
                            Comment = "Great movie!",
                            MovieId = 47,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 124, DateTimeKind.Local).AddTicks(467),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 980995106,
                            Comment = "A masterpiece!",
                            MovieId = 48,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 124, DateTimeKind.Local).AddTicks(492),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -363991299,
                            Comment = "Really enjoyed it.",
                            MovieId = 48,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 124, DateTimeKind.Local).AddTicks(514),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 236646209,
                            Comment = "Would not recommend.",
                            MovieId = 49,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 124, DateTimeKind.Local).AddTicks(537),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1538926406,
                            Comment = "A masterpiece!",
                            MovieId = 49,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 124, DateTimeKind.Local).AddTicks(560),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -531583901,
                            Comment = "Not bad, but could be better.",
                            MovieId = 50,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 124, DateTimeKind.Local).AddTicks(583),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 863746379,
                            Comment = "Not bad, but could be better.",
                            MovieId = 50,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 8, 23, 43, 50, 124, DateTimeKind.Local).AddTicks(606),
                            UserId = "3"
                        });
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Streaming", b =>
                {
                    b.Property<int>("StreamingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StreamingId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StreamingId");

                    b.ToTable("Streamings");

                    b.HasData(
                        new
                        {
                            StreamingId = 1,
                            Name = "Netflix"
                        },
                        new
                        {
                            StreamingId = 2,
                            Name = "Amazon Prime Video"
                        },
                        new
                        {
                            StreamingId = 3,
                            Name = "Disney+"
                        },
                        new
                        {
                            StreamingId = 4,
                            Name = "HBO Max"
                        },
                        new
                        {
                            StreamingId = 5,
                            Name = "Hulu"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Movie", b =>
                {
                    b.HasOne("MovieCatalogMVC.Entities.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.MoviesStreamings", b =>
                {
                    b.HasOne("MovieCatalogMVC.Entities.Movie", "Movie")
                        .WithMany("MoviesStreamings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieCatalogMVC.Entities.Streaming", "Streaming")
                        .WithMany("MoviesStreamings")
                        .HasForeignKey("StreamingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Streaming");
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Review", b =>
                {
                    b.HasOne("MovieCatalogMVC.Entities.Movie", "Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Movie", b =>
                {
                    b.Navigation("MoviesStreamings");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Streaming", b =>
                {
                    b.Navigation("MoviesStreamings");
                });
#pragma warning restore 612, 618
        }
    }
}
