// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieCatalogMVC.Data;

#nullable disable

namespace MovieCatalogMVC.Data.Migrations
{
    [DbContext(typeof(MovieCatalogMVCContext))]
    [Migration("20240909030901_ReviewUserFix")]
    partial class ReviewUserFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c2044697-286c-48cb-bba3-d8c9991eddb6",
                            Email = "user1@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@EXAMPLE.COM",
                            NormalizedUserName = "USER1@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEORDqxl9Bi655N0GAnL0GMhqgOJxX06t/QM0wtkmzQo8aELeY++3XWpUb2Kajy+r2A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d3ad413b-4dbf-4fa1-adac-73e855dac76d",
                            TwoFactorEnabled = false,
                            UserName = "user1@example.com"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a21c5bb3-cefa-4bff-8345-e1354f991709",
                            Email = "user2@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER2@EXAMPLE.COM",
                            NormalizedUserName = "USER2@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBqduzW0FDe+DjvCaVYFHe4JNIhoLYrdbzXfSm3JYztEXmNXCdv956MA2BrWaNi6/w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "042563de-f743-44a1-9ba7-321f6e7914f4",
                            TwoFactorEnabled = false,
                            UserName = "user2@example.com"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a8a1e35a-2e74-4df5-bf03-435dfe99fa67",
                            Email = "user3@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER3@EXAMPLE.COM",
                            NormalizedUserName = "USER3@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGy5AIUzA/t5kfrlEi//2+SbMRfiFiSOEGzQsW36bk9NfhNngHZG160OH3P16Zk0Pw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b6c650ae-70c7-41cf-8a77-22fb666a5774",
                            TwoFactorEnabled = false,
                            UserName = "user3@example.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Name = "Action"
                        },
                        new
                        {
                            GenreId = 2,
                            Name = "Comedy"
                        },
                        new
                        {
                            GenreId = 3,
                            Name = "Drama"
                        },
                        new
                        {
                            GenreId = 4,
                            Name = "Fantasy"
                        },
                        new
                        {
                            GenreId = 5,
                            Name = "Horror"
                        },
                        new
                        {
                            GenreId = 6,
                            Name = "Mystery"
                        },
                        new
                        {
                            GenreId = 7,
                            Name = "Romance"
                        },
                        new
                        {
                            GenreId = 8,
                            Name = "Thriller"
                        },
                        new
                        {
                            GenreId = 9,
                            Name = "Western"
                        },
                        new
                        {
                            GenreId = 10,
                            Name = "Documentary"
                        },
                        new
                        {
                            GenreId = 11,
                            Name = "Animation"
                        },
                        new
                        {
                            GenreId = 12,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            GenreId = 13,
                            Name = "Adventure"
                        },
                        new
                        {
                            GenreId = 14,
                            Name = "Crime"
                        },
                        new
                        {
                            GenreId = 15,
                            Name = "Musical"
                        });
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            GenreId = 1,
                            ReleaseDate = new DateTime(2015, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mad Max: Fury Road"
                        },
                        new
                        {
                            MovieId = 2,
                            GenreId = 1,
                            ReleaseDate = new DateTime(2014, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "John Wick"
                        },
                        new
                        {
                            MovieId = 3,
                            GenreId = 1,
                            ReleaseDate = new DateTime(1988, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Die Hard"
                        },
                        new
                        {
                            MovieId = 4,
                            GenreId = 1,
                            ReleaseDate = new DateTime(2008, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            MovieId = 5,
                            GenreId = 2,
                            ReleaseDate = new DateTime(2007, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Superbad"
                        },
                        new
                        {
                            MovieId = 6,
                            GenreId = 2,
                            ReleaseDate = new DateTime(2014, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Grand Budapest Hotel"
                        },
                        new
                        {
                            MovieId = 7,
                            GenreId = 2,
                            ReleaseDate = new DateTime(2008, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Step Brothers"
                        },
                        new
                        {
                            MovieId = 8,
                            GenreId = 2,
                            ReleaseDate = new DateTime(2004, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Anchorman: The Legend of Ron Burgundy"
                        },
                        new
                        {
                            MovieId = 9,
                            GenreId = 3,
                            ReleaseDate = new DateTime(1994, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            MovieId = 10,
                            GenreId = 3,
                            ReleaseDate = new DateTime(1994, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            MovieId = 11,
                            GenreId = 3,
                            ReleaseDate = new DateTime(1972, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Godfather"
                        },
                        new
                        {
                            MovieId = 12,
                            GenreId = 3,
                            ReleaseDate = new DateTime(2001, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "A Beautiful Mind"
                        },
                        new
                        {
                            MovieId = 13,
                            GenreId = 4,
                            ReleaseDate = new DateTime(2001, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Lord of the Rings: The Fellowship of the Ring"
                        },
                        new
                        {
                            MovieId = 14,
                            GenreId = 4,
                            ReleaseDate = new DateTime(2001, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            MovieId = 15,
                            GenreId = 4,
                            ReleaseDate = new DateTime(2006, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pan's Labyrinth"
                        },
                        new
                        {
                            MovieId = 16,
                            GenreId = 4,
                            ReleaseDate = new DateTime(2001, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Spirited Away"
                        },
                        new
                        {
                            MovieId = 17,
                            GenreId = 5,
                            ReleaseDate = new DateTime(1973, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Exorcist"
                        },
                        new
                        {
                            MovieId = 18,
                            GenreId = 5,
                            ReleaseDate = new DateTime(2017, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Get Out"
                        },
                        new
                        {
                            MovieId = 19,
                            GenreId = 5,
                            ReleaseDate = new DateTime(2018, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "A Quiet Place"
                        },
                        new
                        {
                            MovieId = 20,
                            GenreId = 5,
                            ReleaseDate = new DateTime(2018, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hereditary"
                        },
                        new
                        {
                            MovieId = 21,
                            GenreId = 6,
                            ReleaseDate = new DateTime(2019, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Knives Out"
                        },
                        new
                        {
                            MovieId = 22,
                            GenreId = 6,
                            ReleaseDate = new DateTime(1995, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Se7en"
                        },
                        new
                        {
                            MovieId = 23,
                            GenreId = 6,
                            ReleaseDate = new DateTime(2014, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gone Girl"
                        },
                        new
                        {
                            MovieId = 24,
                            GenreId = 7,
                            ReleaseDate = new DateTime(2004, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Notebook"
                        },
                        new
                        {
                            MovieId = 25,
                            GenreId = 7,
                            ReleaseDate = new DateTime(2005, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            MovieId = 26,
                            GenreId = 7,
                            ReleaseDate = new DateTime(2016, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "La La Land"
                        },
                        new
                        {
                            MovieId = 27,
                            GenreId = 8,
                            ReleaseDate = new DateTime(1991, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Silence of the Lambs"
                        },
                        new
                        {
                            MovieId = 28,
                            GenreId = 8,
                            ReleaseDate = new DateTime(1999, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fight Club"
                        },
                        new
                        {
                            MovieId = 29,
                            GenreId = 8,
                            ReleaseDate = new DateTime(2013, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Prisoners"
                        },
                        new
                        {
                            MovieId = 30,
                            GenreId = 9,
                            ReleaseDate = new DateTime(1966, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Good, the Bad and the Ugly"
                        },
                        new
                        {
                            MovieId = 31,
                            GenreId = 9,
                            ReleaseDate = new DateTime(1992, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Unforgiven"
                        },
                        new
                        {
                            MovieId = 32,
                            GenreId = 9,
                            ReleaseDate = new DateTime(2010, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "True Grit"
                        },
                        new
                        {
                            MovieId = 33,
                            GenreId = 10,
                            ReleaseDate = new DateTime(2016, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "13th"
                        },
                        new
                        {
                            MovieId = 34,
                            GenreId = 10,
                            ReleaseDate = new DateTime(2018, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Free Solo"
                        },
                        new
                        {
                            MovieId = 35,
                            GenreId = 10,
                            ReleaseDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Social Dilemma"
                        },
                        new
                        {
                            MovieId = 36,
                            GenreId = 11,
                            ReleaseDate = new DateTime(1995, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Toy Story"
                        },
                        new
                        {
                            MovieId = 37,
                            GenreId = 11,
                            ReleaseDate = new DateTime(2003, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Finding Nemo"
                        },
                        new
                        {
                            MovieId = 38,
                            GenreId = 11,
                            ReleaseDate = new DateTime(2001, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Spirited Away"
                        },
                        new
                        {
                            MovieId = 39,
                            GenreId = 12,
                            ReleaseDate = new DateTime(2010, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception"
                        },
                        new
                        {
                            MovieId = 40,
                            GenreId = 12,
                            ReleaseDate = new DateTime(2017, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Blade Runner 2049"
                        },
                        new
                        {
                            MovieId = 41,
                            GenreId = 12,
                            ReleaseDate = new DateTime(1999, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Matrix"
                        },
                        new
                        {
                            MovieId = 42,
                            GenreId = 13,
                            ReleaseDate = new DateTime(1993, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jurassic Park"
                        },
                        new
                        {
                            MovieId = 43,
                            GenreId = 13,
                            ReleaseDate = new DateTime(1981, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Indiana Jones: Raiders of the Lost Ark"
                        },
                        new
                        {
                            MovieId = 44,
                            GenreId = 13,
                            ReleaseDate = new DateTime(1995, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jumanji"
                        },
                        new
                        {
                            MovieId = 45,
                            GenreId = 14,
                            ReleaseDate = new DateTime(1972, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Godfather"
                        },
                        new
                        {
                            MovieId = 46,
                            GenreId = 14,
                            ReleaseDate = new DateTime(1990, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Goodfellas"
                        },
                        new
                        {
                            MovieId = 47,
                            GenreId = 14,
                            ReleaseDate = new DateTime(1994, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            MovieId = 48,
                            GenreId = 15,
                            ReleaseDate = new DateTime(1965, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Sound of Music"
                        },
                        new
                        {
                            MovieId = 49,
                            GenreId = 15,
                            ReleaseDate = new DateTime(2016, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "La La Land"
                        },
                        new
                        {
                            MovieId = 50,
                            GenreId = 15,
                            ReleaseDate = new DateTime(2002, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Chicago"
                        });
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.MoviesStreamings", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("StreamingId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "StreamingId");

                    b.HasIndex("StreamingId");

                    b.ToTable("MoviesStreamings");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 1,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 2,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 2,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 3,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 3,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 4,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 4,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 5,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 6,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 7,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 7,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 8,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 9,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 9,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 10,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 11,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 12,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 13,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 14,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 15,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 16,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 17,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 18,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 19,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 20,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 21,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 22,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 23,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 24,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 25,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 26,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 27,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 28,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 29,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 30,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 31,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 32,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 33,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 34,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 35,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 36,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 37,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 38,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 39,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 40,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 41,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 42,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 43,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 44,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 45,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 46,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 47,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 48,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 49,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 50,
                            StreamingId = 5
                        });
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReviewId");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = -1949664316,
                            Comment = "A masterpiece!",
                            MovieId = 1,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 40, DateTimeKind.Local).AddTicks(4295),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -63262785,
                            Comment = "",
                            MovieId = 1,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(268),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1000728698,
                            Comment = "",
                            MovieId = 2,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(309),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1180345652,
                            Comment = "",
                            MovieId = 2,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(345),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1552119319,
                            Comment = "Would not recommend.",
                            MovieId = 3,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(382),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 1042064542,
                            Comment = "Really enjoyed it.",
                            MovieId = 3,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(419),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -683547773,
                            Comment = "",
                            MovieId = 4,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(454),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -2020048327,
                            Comment = "A masterpiece!",
                            MovieId = 4,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(478),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -1315666479,
                            Comment = "Really enjoyed it.",
                            MovieId = 5,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(525),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -1901508636,
                            Comment = "Would not recommend.",
                            MovieId = 5,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(591),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 866274981,
                            Comment = "A masterpiece!",
                            MovieId = 6,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(618),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -1845699736,
                            Comment = "A masterpiece!",
                            MovieId = 6,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(647),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -498021567,
                            Comment = "A masterpiece!",
                            MovieId = 7,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(676),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1793127234,
                            Comment = "Not bad, but could be better.",
                            MovieId = 7,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(732),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 1042980575,
                            Comment = "",
                            MovieId = 8,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(761),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -880967854,
                            Comment = "A masterpiece!",
                            MovieId = 8,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(792),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 1251042358,
                            Comment = "",
                            MovieId = 9,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(816),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -1378549022,
                            Comment = "A masterpiece!",
                            MovieId = 9,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(842),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -201965260,
                            Comment = "",
                            MovieId = 10,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(867),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 689116190,
                            Comment = "Would not recommend.",
                            MovieId = 10,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(890),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1298511331,
                            Comment = "A masterpiece!",
                            MovieId = 11,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(916),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -1109671825,
                            Comment = "Not bad, but could be better.",
                            MovieId = 11,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(940),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 469691313,
                            Comment = "Not bad, but could be better.",
                            MovieId = 12,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(963),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -1078423083,
                            Comment = "Would not recommend.",
                            MovieId = 12,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(987),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -1897899896,
                            Comment = "Not bad, but could be better.",
                            MovieId = 13,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1010),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1686332801,
                            Comment = "",
                            MovieId = 13,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1038),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -755467274,
                            Comment = "Really enjoyed it.",
                            MovieId = 14,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1062),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -2114253428,
                            Comment = "",
                            MovieId = 14,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1108),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -2098329563,
                            Comment = "Not bad, but could be better.",
                            MovieId = 15,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1168),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -1419506644,
                            Comment = "Really enjoyed it.",
                            MovieId = 15,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1203),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -1257468117,
                            Comment = "",
                            MovieId = 16,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1238),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 218561123,
                            Comment = "Great movie!",
                            MovieId = 16,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1264),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -1409578747,
                            Comment = "Great movie!",
                            MovieId = 17,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1288),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 414830437,
                            Comment = "Would not recommend.",
                            MovieId = 17,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1340),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -1998371247,
                            Comment = "Really enjoyed it.",
                            MovieId = 18,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1366),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -253558129,
                            Comment = "Great movie!",
                            MovieId = 18,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1390),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 566202988,
                            Comment = "Not bad, but could be better.",
                            MovieId = 19,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1418),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1728104605,
                            Comment = "",
                            MovieId = 19,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1442),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 1900278091,
                            Comment = "Would not recommend.",
                            MovieId = 20,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1466),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1945012091,
                            Comment = "",
                            MovieId = 20,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1489),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 514254592,
                            Comment = "Not bad, but could be better.",
                            MovieId = 21,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1513),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -1503281918,
                            Comment = "Not bad, but could be better.",
                            MovieId = 21,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1537),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -1805598415,
                            Comment = "Great movie!",
                            MovieId = 22,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1560),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -439472186,
                            Comment = "Great movie!",
                            MovieId = 22,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1584),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -1350271445,
                            Comment = "A masterpiece!",
                            MovieId = 23,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1610),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -977117385,
                            Comment = "Not bad, but could be better.",
                            MovieId = 23,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1634),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -1381376148,
                            Comment = "Great movie!",
                            MovieId = 24,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1658),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -1606702394,
                            Comment = "Really enjoyed it.",
                            MovieId = 24,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1682),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 786665187,
                            Comment = "A masterpiece!",
                            MovieId = 25,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1706),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1494014245,
                            Comment = "Really enjoyed it.",
                            MovieId = 25,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1729),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 164476665,
                            Comment = "Not bad, but could be better.",
                            MovieId = 26,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1754),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1293131027,
                            Comment = "Great movie!",
                            MovieId = 26,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1777),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1684033805,
                            Comment = "A masterpiece!",
                            MovieId = 27,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1803),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -112317479,
                            Comment = "",
                            MovieId = 27,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1826),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1690926553,
                            Comment = "Not bad, but could be better.",
                            MovieId = 28,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1850),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -461243488,
                            Comment = "A masterpiece!",
                            MovieId = 28,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1874),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 2021478111,
                            Comment = "Really enjoyed it.",
                            MovieId = 29,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1898),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1291733136,
                            Comment = "Not bad, but could be better.",
                            MovieId = 29,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1921),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -550528544,
                            Comment = "Really enjoyed it.",
                            MovieId = 30,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1949),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1194611681,
                            Comment = "Great movie!",
                            MovieId = 30,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(1973),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1086121076,
                            Comment = "",
                            MovieId = 31,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2014),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 841961860,
                            Comment = "Not bad, but could be better.",
                            MovieId = 31,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2038),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 743525963,
                            Comment = "Would not recommend.",
                            MovieId = 32,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2062),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 1362200786,
                            Comment = "Great movie!",
                            MovieId = 32,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2086),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -896715856,
                            Comment = "Would not recommend.",
                            MovieId = 33,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2109),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -884179571,
                            Comment = "Really enjoyed it.",
                            MovieId = 33,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2136),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -64590786,
                            Comment = "Not bad, but could be better.",
                            MovieId = 34,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2160),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 1910753633,
                            Comment = "Not bad, but could be better.",
                            MovieId = 34,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2183),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 958102546,
                            Comment = "Would not recommend.",
                            MovieId = 35,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2209),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -1569710433,
                            Comment = "A masterpiece!",
                            MovieId = 35,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2232),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 269443040,
                            Comment = "Not bad, but could be better.",
                            MovieId = 36,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2256),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -626093365,
                            Comment = "Not bad, but could be better.",
                            MovieId = 36,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2279),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -1717745230,
                            Comment = "Would not recommend.",
                            MovieId = 37,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2303),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -423744754,
                            Comment = "Really enjoyed it.",
                            MovieId = 37,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2327),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 319015261,
                            Comment = "",
                            MovieId = 38,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2350),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 193170724,
                            Comment = "Great movie!",
                            MovieId = 38,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2374),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -453211799,
                            Comment = "Would not recommend.",
                            MovieId = 39,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2400),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -985339848,
                            Comment = "Not bad, but could be better.",
                            MovieId = 39,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2424),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1274251667,
                            Comment = "A masterpiece!",
                            MovieId = 40,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2448),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -181826915,
                            Comment = "Would not recommend.",
                            MovieId = 40,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2472),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -307066675,
                            Comment = "Would not recommend.",
                            MovieId = 41,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2496),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -1172892621,
                            Comment = "A masterpiece!",
                            MovieId = 41,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2520),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -885465714,
                            Comment = "Would not recommend.",
                            MovieId = 42,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2543),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -671231904,
                            Comment = "Really enjoyed it.",
                            MovieId = 42,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2633),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 799760484,
                            Comment = "A masterpiece!",
                            MovieId = 43,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2660),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1792362025,
                            Comment = "Not bad, but could be better.",
                            MovieId = 43,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2684),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1216197910,
                            Comment = "Really enjoyed it.",
                            MovieId = 44,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2708),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -194657207,
                            Comment = "Not bad, but could be better.",
                            MovieId = 44,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2732),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 970266962,
                            Comment = "A masterpiece!",
                            MovieId = 45,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2756),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 105523851,
                            Comment = "Great movie!",
                            MovieId = 45,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2779),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -1084293906,
                            Comment = "Great movie!",
                            MovieId = 46,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2803),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 8230794,
                            Comment = "Not bad, but could be better.",
                            MovieId = 46,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2826),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 6368059,
                            Comment = "Great movie!",
                            MovieId = 47,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2852),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -94592764,
                            Comment = "Really enjoyed it.",
                            MovieId = 47,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2875),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -472328871,
                            Comment = "",
                            MovieId = 48,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2899),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -6640397,
                            Comment = "Really enjoyed it.",
                            MovieId = 48,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2922),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 829379965,
                            Comment = "Not bad, but could be better.",
                            MovieId = 49,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2946),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -727713645,
                            Comment = "Would not recommend.",
                            MovieId = 49,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2969),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 695570157,
                            Comment = "Really enjoyed it.",
                            MovieId = 50,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(2993),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 330151347,
                            Comment = "Not bad, but could be better.",
                            MovieId = 50,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 9, 1, 41, DateTimeKind.Local).AddTicks(3017),
                            UserId = "1"
                        });
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Streaming", b =>
                {
                    b.Property<int>("StreamingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StreamingId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StreamingId");

                    b.ToTable("Streamings");

                    b.HasData(
                        new
                        {
                            StreamingId = 1,
                            Name = "Netflix"
                        },
                        new
                        {
                            StreamingId = 2,
                            Name = "Amazon Prime Video"
                        },
                        new
                        {
                            StreamingId = 3,
                            Name = "Disney+"
                        },
                        new
                        {
                            StreamingId = 4,
                            Name = "HBO Max"
                        },
                        new
                        {
                            StreamingId = 5,
                            Name = "Hulu"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Movie", b =>
                {
                    b.HasOne("MovieCatalogMVC.Entities.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.MoviesStreamings", b =>
                {
                    b.HasOne("MovieCatalogMVC.Entities.Movie", "Movie")
                        .WithMany("MoviesStreamings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieCatalogMVC.Entities.Streaming", "Streaming")
                        .WithMany("MoviesStreamings")
                        .HasForeignKey("StreamingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Streaming");
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Review", b =>
                {
                    b.HasOne("MovieCatalogMVC.Entities.Movie", "Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Movie", b =>
                {
                    b.Navigation("MoviesStreamings");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Streaming", b =>
                {
                    b.Navigation("MoviesStreamings");
                });
#pragma warning restore 612, 618
        }
    }
}
