// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieCatalogMVC.Data;

#nullable disable

namespace MovieCatalogMVC.Data.Migrations
{
    [DbContext(typeof(MovieCatalogMVCContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            Email = "user1@example.com",
                            EmailConfirmed = true,
                            NormalizedEmail = "USER1@EXAMPLE.COM",
                            NormalizedUserName = "USER1@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENlLm+JDqrXf2EJLbvREHO4BZTusrX6td48UDuvoZMfy+mnxERW45E69Ih2jofvqMA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d18abe43-1c4c-40c8-b1b6-9037d4f5583f",
                            TwoFactorEnabled = false,
                            UserName = "user1@example.com"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            Email = "user2@example.com",
                            EmailConfirmed = true,
                            NormalizedEmail = "USER2@EXAMPLE.COM",
                            NormalizedUserName = "USER2@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJD47ZInq16gGf/6Tyh0Zf/A4ftgFkQg2rFneqQAF/MU5wAlEthpZLpdikcXmNHRkQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ecb47140-7a36-4cd3-aaa9-b595a751dfb1",
                            TwoFactorEnabled = false,
                            UserName = "user2@example.com"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            Email = "user3@example.com",
                            EmailConfirmed = true,
                            NormalizedEmail = "USER3@EXAMPLE.COM",
                            NormalizedUserName = "USER3@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMSX8kP7MVp8APDDSiercRx0XzkS+SMnT25NOZrncvSYDYf54pR29V0/RxRRyBa8kA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "750e7b4f-3bfc-4332-a59f-acfee536d00a",
                            TwoFactorEnabled = false,
                            UserName = "user3@example.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Name = "Action"
                        },
                        new
                        {
                            GenreId = 2,
                            Name = "Comedy"
                        },
                        new
                        {
                            GenreId = 3,
                            Name = "Drama"
                        },
                        new
                        {
                            GenreId = 4,
                            Name = "Fantasy"
                        },
                        new
                        {
                            GenreId = 5,
                            Name = "Horror"
                        },
                        new
                        {
                            GenreId = 6,
                            Name = "Mystery"
                        },
                        new
                        {
                            GenreId = 7,
                            Name = "Romance"
                        },
                        new
                        {
                            GenreId = 8,
                            Name = "Thriller"
                        },
                        new
                        {
                            GenreId = 9,
                            Name = "Western"
                        },
                        new
                        {
                            GenreId = 10,
                            Name = "Documentary"
                        },
                        new
                        {
                            GenreId = 11,
                            Name = "Animation"
                        },
                        new
                        {
                            GenreId = 12,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            GenreId = 13,
                            Name = "Adventure"
                        },
                        new
                        {
                            GenreId = 14,
                            Name = "Crime"
                        },
                        new
                        {
                            GenreId = 15,
                            Name = "Musical"
                        });
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            GenreId = 1,
                            ReleaseDate = new DateTime(2015, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mad Max: Fury Road"
                        },
                        new
                        {
                            MovieId = 2,
                            GenreId = 1,
                            ReleaseDate = new DateTime(2014, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "John Wick"
                        },
                        new
                        {
                            MovieId = 3,
                            GenreId = 1,
                            ReleaseDate = new DateTime(1988, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Die Hard"
                        },
                        new
                        {
                            MovieId = 4,
                            GenreId = 1,
                            ReleaseDate = new DateTime(2008, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            MovieId = 5,
                            GenreId = 2,
                            ReleaseDate = new DateTime(2007, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Superbad"
                        },
                        new
                        {
                            MovieId = 6,
                            GenreId = 2,
                            ReleaseDate = new DateTime(2014, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Grand Budapest Hotel"
                        },
                        new
                        {
                            MovieId = 7,
                            GenreId = 2,
                            ReleaseDate = new DateTime(2008, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Step Brothers"
                        },
                        new
                        {
                            MovieId = 8,
                            GenreId = 2,
                            ReleaseDate = new DateTime(2004, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Anchorman: The Legend of Ron Burgundy"
                        },
                        new
                        {
                            MovieId = 9,
                            GenreId = 3,
                            ReleaseDate = new DateTime(1994, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            MovieId = 10,
                            GenreId = 3,
                            ReleaseDate = new DateTime(1994, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            MovieId = 11,
                            GenreId = 3,
                            ReleaseDate = new DateTime(1972, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Godfather"
                        },
                        new
                        {
                            MovieId = 12,
                            GenreId = 3,
                            ReleaseDate = new DateTime(2001, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "A Beautiful Mind"
                        },
                        new
                        {
                            MovieId = 13,
                            GenreId = 4,
                            ReleaseDate = new DateTime(2001, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Lord of the Rings: The Fellowship of the Ring"
                        },
                        new
                        {
                            MovieId = 14,
                            GenreId = 4,
                            ReleaseDate = new DateTime(2001, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            MovieId = 15,
                            GenreId = 4,
                            ReleaseDate = new DateTime(2006, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pan's Labyrinth"
                        },
                        new
                        {
                            MovieId = 16,
                            GenreId = 4,
                            ReleaseDate = new DateTime(2001, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Spirited Away"
                        },
                        new
                        {
                            MovieId = 17,
                            GenreId = 5,
                            ReleaseDate = new DateTime(1973, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Exorcist"
                        },
                        new
                        {
                            MovieId = 18,
                            GenreId = 5,
                            ReleaseDate = new DateTime(2017, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Get Out"
                        },
                        new
                        {
                            MovieId = 19,
                            GenreId = 5,
                            ReleaseDate = new DateTime(2018, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "A Quiet Place"
                        },
                        new
                        {
                            MovieId = 20,
                            GenreId = 5,
                            ReleaseDate = new DateTime(2018, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hereditary"
                        },
                        new
                        {
                            MovieId = 21,
                            GenreId = 6,
                            ReleaseDate = new DateTime(2019, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Knives Out"
                        },
                        new
                        {
                            MovieId = 22,
                            GenreId = 6,
                            ReleaseDate = new DateTime(1995, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Se7en"
                        },
                        new
                        {
                            MovieId = 23,
                            GenreId = 6,
                            ReleaseDate = new DateTime(2014, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gone Girl"
                        },
                        new
                        {
                            MovieId = 24,
                            GenreId = 7,
                            ReleaseDate = new DateTime(2004, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Notebook"
                        },
                        new
                        {
                            MovieId = 25,
                            GenreId = 7,
                            ReleaseDate = new DateTime(2005, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            MovieId = 26,
                            GenreId = 7,
                            ReleaseDate = new DateTime(2016, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "La La Land"
                        },
                        new
                        {
                            MovieId = 27,
                            GenreId = 8,
                            ReleaseDate = new DateTime(1991, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Silence of the Lambs"
                        },
                        new
                        {
                            MovieId = 28,
                            GenreId = 8,
                            ReleaseDate = new DateTime(1999, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fight Club"
                        },
                        new
                        {
                            MovieId = 29,
                            GenreId = 8,
                            ReleaseDate = new DateTime(2013, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Prisoners"
                        },
                        new
                        {
                            MovieId = 30,
                            GenreId = 9,
                            ReleaseDate = new DateTime(1966, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Good, the Bad and the Ugly"
                        },
                        new
                        {
                            MovieId = 31,
                            GenreId = 9,
                            ReleaseDate = new DateTime(1992, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Unforgiven"
                        },
                        new
                        {
                            MovieId = 32,
                            GenreId = 9,
                            ReleaseDate = new DateTime(2010, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "True Grit"
                        },
                        new
                        {
                            MovieId = 33,
                            GenreId = 10,
                            ReleaseDate = new DateTime(2016, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "13th"
                        },
                        new
                        {
                            MovieId = 34,
                            GenreId = 10,
                            ReleaseDate = new DateTime(2018, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Free Solo"
                        },
                        new
                        {
                            MovieId = 35,
                            GenreId = 10,
                            ReleaseDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Social Dilemma"
                        },
                        new
                        {
                            MovieId = 36,
                            GenreId = 11,
                            ReleaseDate = new DateTime(1995, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Toy Story"
                        },
                        new
                        {
                            MovieId = 37,
                            GenreId = 11,
                            ReleaseDate = new DateTime(2003, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Finding Nemo"
                        },
                        new
                        {
                            MovieId = 38,
                            GenreId = 11,
                            ReleaseDate = new DateTime(2001, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Spirited Away"
                        },
                        new
                        {
                            MovieId = 39,
                            GenreId = 12,
                            ReleaseDate = new DateTime(2010, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception"
                        },
                        new
                        {
                            MovieId = 40,
                            GenreId = 12,
                            ReleaseDate = new DateTime(2017, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Blade Runner 2049"
                        },
                        new
                        {
                            MovieId = 41,
                            GenreId = 12,
                            ReleaseDate = new DateTime(1999, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Matrix"
                        },
                        new
                        {
                            MovieId = 42,
                            GenreId = 13,
                            ReleaseDate = new DateTime(1993, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jurassic Park"
                        },
                        new
                        {
                            MovieId = 43,
                            GenreId = 13,
                            ReleaseDate = new DateTime(1981, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Indiana Jones: Raiders of the Lost Ark"
                        },
                        new
                        {
                            MovieId = 44,
                            GenreId = 13,
                            ReleaseDate = new DateTime(1995, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jumanji"
                        },
                        new
                        {
                            MovieId = 45,
                            GenreId = 14,
                            ReleaseDate = new DateTime(1972, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Godfather"
                        },
                        new
                        {
                            MovieId = 46,
                            GenreId = 14,
                            ReleaseDate = new DateTime(1990, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Goodfellas"
                        },
                        new
                        {
                            MovieId = 47,
                            GenreId = 14,
                            ReleaseDate = new DateTime(1994, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            MovieId = 48,
                            GenreId = 15,
                            ReleaseDate = new DateTime(1965, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Sound of Music"
                        },
                        new
                        {
                            MovieId = 49,
                            GenreId = 15,
                            ReleaseDate = new DateTime(2016, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "La La Land"
                        },
                        new
                        {
                            MovieId = 50,
                            GenreId = 15,
                            ReleaseDate = new DateTime(2002, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Chicago"
                        });
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.MoviesStreamings", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("StreamingId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "StreamingId");

                    b.HasIndex("StreamingId");

                    b.ToTable("MoviesStreamings");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 1,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 2,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 2,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 3,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 3,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 4,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 4,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 5,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 6,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 7,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 7,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 8,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 9,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 9,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 10,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 11,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 12,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 13,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 14,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 15,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 16,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 17,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 18,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 19,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 20,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 21,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 22,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 23,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 24,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 25,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 26,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 27,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 28,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 29,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 30,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 31,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 32,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 33,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 34,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 35,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 36,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 37,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 38,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 39,
                            StreamingId = 5
                        },
                        new
                        {
                            MovieId = 40,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 41,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 42,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 43,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 44,
                            StreamingId = 4
                        },
                        new
                        {
                            MovieId = 45,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 46,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 47,
                            StreamingId = 1
                        },
                        new
                        {
                            MovieId = 48,
                            StreamingId = 2
                        },
                        new
                        {
                            MovieId = 49,
                            StreamingId = 3
                        },
                        new
                        {
                            MovieId = 50,
                            StreamingId = 5
                        });
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReviewId");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1242211164,
                            Comment = "Would not recommend.",
                            MovieId = 1,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 449, DateTimeKind.Local).AddTicks(8578),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -1947654451,
                            Comment = "Great movie!",
                            MovieId = 1,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 449, DateTimeKind.Local).AddTicks(8992),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 623362243,
                            Comment = "Would not recommend.",
                            MovieId = 2,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 449, DateTimeKind.Local).AddTicks(9030),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 888510509,
                            Comment = "Not bad, but could be better.",
                            MovieId = 2,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 449, DateTimeKind.Local).AddTicks(9061),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -48385073,
                            Comment = "",
                            MovieId = 3,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 449, DateTimeKind.Local).AddTicks(9102),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -1600929322,
                            Comment = "A masterpiece!",
                            MovieId = 3,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 449, DateTimeKind.Local).AddTicks(9151),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 135499746,
                            Comment = "Not bad, but could be better.",
                            MovieId = 4,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 449, DateTimeKind.Local).AddTicks(9239),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1438170450,
                            Comment = "Would not recommend.",
                            MovieId = 4,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 449, DateTimeKind.Local).AddTicks(9266),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -825648482,
                            Comment = "Really enjoyed it.",
                            MovieId = 5,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 449, DateTimeKind.Local).AddTicks(9293),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 1318888990,
                            Comment = "A masterpiece!",
                            MovieId = 5,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 449, DateTimeKind.Local).AddTicks(9318),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -951431974,
                            Comment = "A masterpiece!",
                            MovieId = 6,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 449, DateTimeKind.Local).AddTicks(9383),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1133701876,
                            Comment = "",
                            MovieId = 6,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 449, DateTimeKind.Local).AddTicks(9499),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 2026554864,
                            Comment = "",
                            MovieId = 7,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 449, DateTimeKind.Local).AddTicks(9540),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 2080995326,
                            Comment = "Not bad, but could be better.",
                            MovieId = 7,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 449, DateTimeKind.Local).AddTicks(9564),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1095575088,
                            Comment = "",
                            MovieId = 8,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 449, DateTimeKind.Local).AddTicks(9644),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -951044186,
                            Comment = "Really enjoyed it.",
                            MovieId = 8,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 449, DateTimeKind.Local).AddTicks(9691),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -302506736,
                            Comment = "Not bad, but could be better.",
                            MovieId = 9,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 449, DateTimeKind.Local).AddTicks(9714),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -912196359,
                            Comment = "",
                            MovieId = 9,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 449, DateTimeKind.Local).AddTicks(9746),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -767773435,
                            Comment = "",
                            MovieId = 10,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 449, DateTimeKind.Local).AddTicks(9771),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -1572466029,
                            Comment = "Really enjoyed it.",
                            MovieId = 10,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 449, DateTimeKind.Local).AddTicks(9793),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 976382738,
                            Comment = "Really enjoyed it.",
                            MovieId = 11,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 449, DateTimeKind.Local).AddTicks(9828),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 545318525,
                            Comment = "Not bad, but could be better.",
                            MovieId = 11,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 449, DateTimeKind.Local).AddTicks(9852),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 259486811,
                            Comment = "A masterpiece!",
                            MovieId = 12,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 449, DateTimeKind.Local).AddTicks(9874),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 943862476,
                            Comment = "Would not recommend.",
                            MovieId = 12,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 449, DateTimeKind.Local).AddTicks(9896),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -1381750974,
                            Comment = "A masterpiece!",
                            MovieId = 13,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 449, DateTimeKind.Local).AddTicks(9918),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 412933072,
                            Comment = "Not bad, but could be better.",
                            MovieId = 13,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(18),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1912451404,
                            Comment = "A masterpiece!",
                            MovieId = 14,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(129),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1193833036,
                            Comment = "Would not recommend.",
                            MovieId = 14,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(157),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1956857869,
                            Comment = "Really enjoyed it.",
                            MovieId = 15,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(192),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -165405643,
                            Comment = "A masterpiece!",
                            MovieId = 15,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(236),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -1353580680,
                            Comment = "Would not recommend.",
                            MovieId = 16,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(288),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -1362085066,
                            Comment = "Not bad, but could be better.",
                            MovieId = 16,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(313),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -643318668,
                            Comment = "Great movie!",
                            MovieId = 17,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(337),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 198632095,
                            Comment = "",
                            MovieId = 17,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(362),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -779433463,
                            Comment = "Great movie!",
                            MovieId = 18,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(386),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 427206422,
                            Comment = "Not bad, but could be better.",
                            MovieId = 18,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(408),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1093845674,
                            Comment = "Really enjoyed it.",
                            MovieId = 19,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(431),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 1645285789,
                            Comment = "",
                            MovieId = 19,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(456),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 1564358405,
                            Comment = "",
                            MovieId = 20,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(532),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 2120378525,
                            Comment = "A masterpiece!",
                            MovieId = 20,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(555),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 108876063,
                            Comment = "Great movie!",
                            MovieId = 21,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(578),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -1100453066,
                            Comment = "Would not recommend.",
                            MovieId = 21,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(601),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -1770074713,
                            Comment = "A masterpiece!",
                            MovieId = 22,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(624),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1366128753,
                            Comment = "Would not recommend.",
                            MovieId = 22,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(647),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 553945859,
                            Comment = "Would not recommend.",
                            MovieId = 23,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(670),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 1443748763,
                            Comment = "",
                            MovieId = 23,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(695),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -867833455,
                            Comment = "Great movie!",
                            MovieId = 24,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(718),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -498291209,
                            Comment = "Really enjoyed it.",
                            MovieId = 24,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(741),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 773025134,
                            Comment = "Would not recommend.",
                            MovieId = 25,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(764),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -1060307603,
                            Comment = "A masterpiece!",
                            MovieId = 25,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(787),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 1079146656,
                            Comment = "A masterpiece!",
                            MovieId = 26,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(810),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -753322916,
                            Comment = "Not bad, but could be better.",
                            MovieId = 26,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(833),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 2043804335,
                            Comment = "",
                            MovieId = 27,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(856),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1136792155,
                            Comment = "Great movie!",
                            MovieId = 27,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(881),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 378951104,
                            Comment = "Would not recommend.",
                            MovieId = 28,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(904),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1821241710,
                            Comment = "",
                            MovieId = 28,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(927),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 415658012,
                            Comment = "Great movie!",
                            MovieId = 29,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(950),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1315817723,
                            Comment = "Really enjoyed it.",
                            MovieId = 29,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(973),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -1256600358,
                            Comment = "Great movie!",
                            MovieId = 30,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1003),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1137411169,
                            Comment = "Great movie!",
                            MovieId = 30,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1027),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1095532477,
                            Comment = "Not bad, but could be better.",
                            MovieId = 31,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1051),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 1270356472,
                            Comment = "",
                            MovieId = 31,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1076),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1720144028,
                            Comment = "",
                            MovieId = 32,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1100),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -1504715172,
                            Comment = "",
                            MovieId = 32,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1124),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -236403005,
                            Comment = "Great movie!",
                            MovieId = 33,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1147),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 514833706,
                            Comment = "Really enjoyed it.",
                            MovieId = 33,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1197),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -1443789759,
                            Comment = "Great movie!",
                            MovieId = 34,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1220),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -722260688,
                            Comment = "A masterpiece!",
                            MovieId = 34,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1243),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 544055609,
                            Comment = "Would not recommend.",
                            MovieId = 35,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1266),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -1039094716,
                            Comment = "",
                            MovieId = 35,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1291),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1830895405,
                            Comment = "Really enjoyed it.",
                            MovieId = 36,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1314),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 69929033,
                            Comment = "Would not recommend.",
                            MovieId = 36,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1337),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 335994773,
                            Comment = "Would not recommend.",
                            MovieId = 37,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1360),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 694490099,
                            Comment = "Really enjoyed it.",
                            MovieId = 37,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1383),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1263123311,
                            Comment = "Great movie!",
                            MovieId = 38,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1405),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1343309149,
                            Comment = "A masterpiece!",
                            MovieId = 38,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1428),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -1597534597,
                            Comment = "",
                            MovieId = 39,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1452),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 1406232460,
                            Comment = "Really enjoyed it.",
                            MovieId = 39,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1476),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -1252185896,
                            Comment = "Great movie!",
                            MovieId = 40,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1500),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -282556884,
                            Comment = "",
                            MovieId = 40,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1523),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 634628833,
                            Comment = "A masterpiece!",
                            MovieId = 41,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1545),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -1799824173,
                            Comment = "Great movie!",
                            MovieId = 41,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1568),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -470824750,
                            Comment = "A masterpiece!",
                            MovieId = 42,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1591),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -317083190,
                            Comment = "",
                            MovieId = 42,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1614),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 178217623,
                            Comment = "Really enjoyed it.",
                            MovieId = 43,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1637),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = -414325212,
                            Comment = "",
                            MovieId = 43,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1661),
                            UserId = "3"
                        },
                        new
                        {
                            ReviewId = 811304132,
                            Comment = "Really enjoyed it.",
                            MovieId = 44,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1685),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -97194599,
                            Comment = "Great movie!",
                            MovieId = 44,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1708),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 1118041645,
                            Comment = "Really enjoyed it.",
                            MovieId = 45,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1731),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 1644479121,
                            Comment = "Would not recommend.",
                            MovieId = 45,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1779),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1203101621,
                            Comment = "A masterpiece!",
                            MovieId = 46,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1803),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 1262135024,
                            Comment = "",
                            MovieId = 46,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1826),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -1103699215,
                            Comment = "",
                            MovieId = 47,
                            Rate = 3,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1849),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 221000253,
                            Comment = "A masterpiece!",
                            MovieId = 47,
                            Rate = 5,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1874),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -1832421820,
                            Comment = "Really enjoyed it.",
                            MovieId = 48,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1897),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = 882442979,
                            Comment = "Great movie!",
                            MovieId = 48,
                            Rate = 4,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1920),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -1596385344,
                            Comment = "Great movie!",
                            MovieId = 49,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1944),
                            UserId = "2"
                        },
                        new
                        {
                            ReviewId = -568220298,
                            Comment = "Great movie!",
                            MovieId = 49,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1966),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = -1863839682,
                            Comment = "A masterpiece!",
                            MovieId = 50,
                            Rate = 1,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(1989),
                            UserId = "1"
                        },
                        new
                        {
                            ReviewId = 1473663483,
                            Comment = "Really enjoyed it.",
                            MovieId = 50,
                            Rate = 2,
                            ReviewDate = new DateTime(2024, 9, 9, 0, 16, 2, 450, DateTimeKind.Local).AddTicks(2012),
                            UserId = "1"
                        });
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Streaming", b =>
                {
                    b.Property<int>("StreamingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StreamingId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StreamingId");

                    b.ToTable("Streamings");

                    b.HasData(
                        new
                        {
                            StreamingId = 1,
                            Name = "Netflix"
                        },
                        new
                        {
                            StreamingId = 2,
                            Name = "Amazon Prime Video"
                        },
                        new
                        {
                            StreamingId = 3,
                            Name = "Disney+"
                        },
                        new
                        {
                            StreamingId = 4,
                            Name = "HBO Max"
                        },
                        new
                        {
                            StreamingId = 5,
                            Name = "Hulu"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Movie", b =>
                {
                    b.HasOne("MovieCatalogMVC.Entities.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.MoviesStreamings", b =>
                {
                    b.HasOne("MovieCatalogMVC.Entities.Movie", "Movie")
                        .WithMany("MoviesStreamings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieCatalogMVC.Entities.Streaming", "Streaming")
                        .WithMany("MoviesStreamings")
                        .HasForeignKey("StreamingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Streaming");
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Review", b =>
                {
                    b.HasOne("MovieCatalogMVC.Entities.Movie", "Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Movie", b =>
                {
                    b.Navigation("MoviesStreamings");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MovieCatalogMVC.Entities.Streaming", b =>
                {
                    b.Navigation("MoviesStreamings");
                });
#pragma warning restore 612, 618
        }
    }
}
